### ISSUE TITLE
Can I help u in it

### ISSUE THREAD

**Issue by CoderLogy** [Khhs167/EZlang#3]
Pls let me know

**Comment by Khhs167** [comment]
Yes and no. It is open source, anybody can contribute and create pull requests, but currently i am rewriting, and that part is a no.

**Comment by CoderLogy** [comment]
Ok sorry but I have 2 great advice for you
Pls help us CodersHub in gymcoin and last make a language written in c or
naam otherwise speed and other things would be sad matter as they would be
left
